USE PEOPLE_DB;
CREATE TABLE IF NOT EXISTS PEOPLE1(
p_id INTEGER PRIMARY KEY AUTO_INCREMENT,
p_name VARCHAR(32) NOT NULL,
p_fname VARCHAR(32) NOT NULL,
P_age INTEGER DEFAULT 21 ,
p_cnic VARCHAR(32) UNIQUE,
CONSTRAINT age_constraint CHECK (p_age>=0 AND p_age<=200),
CONSTRAINT name_constraint UNIQUE(p_name,p_fname)


) 