#SHOW DATABASES;
#CREATE DATABASE IF NOT EXISTS PEOPLE_DB;
USE PEOPLE_DB;
#CREATE TABLE IF NOT EXISTS PEOPLE(
#p_id INTEGER PRIMARY KEY AUTO_INCREMENT,
#p_name VARCHAR(50),
#p_DOB DATE,
#p_country ENUM('PAKISTAN','INDIA','AUSTRALIA'));
SHOW TABLES;
#INSERT INTO PEOPLE (p_name, p_DOB,p_country)
#VALUES ('John Doe', '1990-05-15','PAKISTAN');
#UPDATE PEOPLE SET p_name='Usman Arshad' WHERE p_id=2
#DELETE FROM PEOPLE WHERE p_id=3
#ALTER TABLE PEOPLE ADD p_mname TEXT NOT NULL;
#ALTER TABLE PEOPLE MODIFY p_name VARCHAR(100);
#ALTER TABLE PEOPLE RENAME COLUMN p_country TO p_COUNTRY;
#ALTER TABLE PEOPLE DROP COLUMN p_mname
#DROP TABLE PEOPLE
#TRUNCATE TABLE PEOPLE